### ISSUE TITLE
Create public functions to update widgets view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#106]
We need to provide a way to update each widget view by passing an argument containing the data.

For example:
```js
dashboard.widgets.updateCategoryWidget('some-widget-id', data); 
widgetModel.updateView(data);
// data should contain all the necessary attributes for each widget.
```

**Comment by viddo** [comment]
For the afterlife; After conversing offline we agreed to go with following the pattern of adding the public API on the previously returned model (like done for remove[https://github.com/CartoDB/deep-insights.js/pull/93]), i.e. having a `widgetModel` is an obvious prerequisite to be able to update _it_.

E.g. having a category widget:
```js
var catWidget = dashboard.widgets.createCategoryWidget({
  title: 'Testing testing…',
  aggregation: 'count'
})
```

Then one can update it by, probably not too surprisingly:
```js
catWidget.update({
  title: 'Bazinga!',
  collapsed: true,
  aggregation: 'sum'
})
```
Note that only the provides data will be updated, the rest will stay as-is!
The method should throw an Error if data is inconsistent or can't be set for whatever reason.
