### ISSUE TITLE
Widgets get empty but they shouldn't

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#120]
- Go to this example http://localhost:9002/examples/populated-places.html
- Click on select None on the Rank Category Widget.
- Other widgets get empty but they shoulnd't.

**Comment by javisantana** [comment]
Here we have a several problems:

- we should not be showing NONE when there are only 5 categories 
- the label NONE is confusing, it does not make sense to remove all categories but still is hard to see

**Comment by javisantana** [comment]
in the code level: we are including "OTHERS" as part of the model, not sure if we want to do that cc @xavijam

**Comment by saleiva** [comment]
Why not? None is to select no categories so you can select just one after
that with a click

**Comment by javisantana** [comment]
select no categories -> select no categories you see in the list, right?

**Comment by saleiva** [comment]
Nope, its select no categories (without this button would be imposible to
discard categories that you dont see on the list)

**Comment by javisantana** [comment]
so the behavior is ok, if you select no categories the rest of the widgets should not show anything

**Comment by saleiva** [comment]
Well I think we can do it the other way around and remove the "NONE" link.
I propose that we remove the NONE button, we just keep the "ALL" one when not having all the columns selected.

The first click done after having ALL selected, should deactivate all but the one that you have clicked in.

Sounds good?

**Comment by javisantana** [comment]
sounds good, I guess we have a disabled stat for those links

**Comment by saleiva** [comment]
Sure thing. It already behaves like that.
