### ISSUE TITLE
Time series widget doesn't act as filter.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#122]
- go to http://cartodb.github.io/widgets-examples/earthquakes_last_month.html
- Zoom in SF and see how the category and the formula widgets get refreshed with filtered data.
- Now select a range on the Time series widget. The formula doesn't change, neither the category widget.

**Comment by javisantana** [comment]
this is something we need to think about: if we want torque to act as a client side library when we have raster layers as well we can't make it work as a filter

**Comment by saleiva** [comment]
but it's how everything works on the dashboards...

**Comment by javisantana** [comment]
yep, we can change it but we can't aggregate in torque at the same time

**Comment by saleiva** [comment]
@javisantana should we close this?

**Comment by javisantana** [comment]
torque works but the other one is not working yet
