### ISSUE TITLE
Send back the xAxis labels and keep the actual ones on top when filtering the histogram

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#148]
![screen shot 2016-02-09 at 19 32 33](https://cloud.githubusercontent.com/assets/132149/12926483/e3601d20-cf63-11e5-848f-8efd11af2f9e.png)

**Comment by saleiva** [comment]
Since we've removed the small stats, this is quite important now

**Comment by saleiva** [comment]
please :( @xavijam

**Comment by xavijam** [comment]
No prob, assigning to me ;).

**Comment by javierarce** [comment]
I'm not sure what do you want us to do. Do you want to make the labels under the brushes (761K & 1.1M in the example) always visible after dragging?
