### ISSUE TITLE
Update Formula widgets with no metadata on Public View 

### ISSUE THREAD

**Issue by josecruz** [CartoDB/deep-insights.js#154]
E.g:
<img width="363" alt="screen shot 2016-02-10 at 13 59 43" src="https://cloud.githubusercontent.com/assets/596509/12947854/906974a4-cffe-11e5-8ace-f09afbf8693c.png">

Related issues: #147 (histogram) #153 (category)

**Comment by xavijam** [comment]
Duplicated -> https://github.com/CartoDB/deep-insights.js/issues/146
