### ISSUE TITLE
[Histogram widget] lost state after collapsing and expanding the widget

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/deep-insights.js#160]
![histogram](https://cloud.githubusercontent.com/assets/390398/13005226/b32be9c6-d180-11e5-92ea-3c56e8a4d7be.gif)

cc: @xavijam

**Comment by xavijam** [comment]
Seems like histogram is re-rendered again without taking care of the current filters, should it be possible @javierarce?

**Comment by acanimal** [comment]
In addition, values on min, max and avg are lost.
