### ISSUE TITLE
[Formula widget] Operation badget is not being displayed anymore

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/deep-insights.js#161]
I think it's because [we're trying to get the operation from the widget model](https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/formula/content-view.js#L43), but it's actually a property of the dataview model.

cc: @xavijam

**Comment by xavijam** [comment]
cc @viddo

**Comment by viddo** [comment]
Yes that should be `this._dataviewModel.get('operation')` :sob:
