### ISSUE TITLE
 widgets for layers initially hidden are not hidden

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#162]
from solutions, please, @AbelVM complete it

**Comment by AbelVM** [comment]
Widgets linked to a layer with **visible:false** in the di.json are disabled, but still visible

**Comment by acanimal** [comment]
@AbelVM Yesterday we was talking about this issue and it is the behaviour, that is, widgets for a not visible layer are simply disabled but not hidden.

For the moment I close the issue. If you think this behaviour must be changes please let me know to open the issue again and talk.

**Comment by javisantana** [comment]
what "disabled" means? does that mean they still request data?

**Comment by acanimal** [comment]
The are greyed. Not sure if data continues requesting. Checking.

**Comment by acanimal** [comment]
@AbelVM checking again with DI version seems the widgets are toggled off (see image).
@javisantana the bad new are the dataviews continues requesting data. I created this issue https://github.com/CartoDB/cartodb.js/issues/1100

![screen shot 2016-02-16 at 10 02 49](https://cloud.githubusercontent.com/assets/732033/13071580/ba126c12-d494-11e5-923e-6af084f99ef8.png)
