### ISSUE TITLE
race condition when hidding/showing layers

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#163]
cc @abelvm

**Comment by AbelVM** [comment]
Test case:
Two layers, both with linked widgets and a toggle control to change which one is the visible one. So this toggle, hides one and show the other one in two consecutive lines. 
```javascript
                myapp.tx = true;
                cdb.$('#t-data').on('click', function () {
                    myapp.layers[2].set('visible', myapp.tx);
                    myapp.tx = !myapp.tx;
                    myapp.layers[1].set('visible', myapp.tx);
                });
```
This code leads to random behavior: you can get both layers at once, none of them, the right one or the wrong one. Or even view a layer, but the widgets of the other one.

**Comment by acanimal** [comment]
Close due not able to reproduce the issue.
