### ISSUE TITLE
send the initial number of bins set in the viz.json

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#164]
cc @abelvm

**Comment by AbelVM** [comment]
Some parameters need a fixed number of bins, set in config.

Typical: 24h in a day, 7 days in a week, 12 months in a year,...

**Comment by acanimal** [comment]
see also: https://github.com/CartoDB/Windshaft/issues/414

**Comment by rochoa** [comment]
This solves, partially, #71.

**Comment by acanimal** [comment]
Solved in https://github.com/CartoDB/Windshaft/issues/414

**Comment by rochoa** [comment]
Hey, @javisantana made me a proposal about changing the behaviour so we don't need to configure the number of bins but we can send a `bins` when doing the histogram request.

So if you don't send anything it will calculate bins and start+end, if you send bins it will calculate for you the start+end, and if you send bins and start+end will use all provided values.

What do you think @acanimal? Going with that approach means that we need to change deep-insights.

**Comment by acanimal** [comment]
Sound good for me and think it will be transparent for DI.

As a summary, the current issue is because you can configure in dijson a widget with 10 bins. The initial request looks like `server_address?bins=10` but the number is ignored and data with, for example, 48 bins is returned. Then that number of bins is set on the widget and all subsequent request passes that value.

**Comment by rochoa** [comment]
@acanimal I did the required changes in https://github.com/CartoDB/Windshaft/pull/433, can you verify that deep-insights still has the expected behaviour with latest windshaft master branch.

**Comment by acanimal** [comment]
Sorry, I can't verify with master, but they should be transparent for DI. DI simply stores the bucket number returned by the server. If now they are the same than the requested that would be fine.

**Comment by rochoa** [comment]
Why you cannot verify it with master?

**Comment by javisantana** [comment]
@acanimal could you test this locally please? we have a bunch of tickets related to bins we should close

**Comment by acanimal** [comment]
As we talk the change is transparent for DI. Now the histogram is drawn with the specified number of bins in the diJSON:

![screen shot 2016-02-18 at 10 25 09](https://cloud.githubusercontent.com/assets/732033/13138902/0001dfaa-d62a-11e5-8412-8dd3c2819b40.png)

**Comment by AbelVM** [comment]
Does it works with latest DI as is? Which params do I need to set up in the
json?

**Comment by acanimal** [comment]
@AbelVM You need to wait until a new windshaft deployment. For DI is transparent simply set the bins number on the diJSON.

**Comment by AbelVM** [comment]
No need for extra params as start, end...?

**Comment by acanimal** [comment]
No for the moment, only bins are taking into account.
@rochoa are you workin on https://github.com/CartoDB/deep-insights.js/issues/164#issuecomment-184658816 ?

**Comment by rochoa** [comment]
What is your question? I don't understand it. The changes proposed https://github.com/CartoDB/deep-insights.js/issues/164#issuecomment-184658816 were implemented as per https://github.com/CartoDB/deep-insights.js/issues/164#issuecomment-185141322. I just wanted to know if that was working with DI so we can release windshaft with those changes.

I think @AbelVM is asking if it's possible to fix the number of bins, start, and end at DI level. Windshaft supports all of them right now, but I don't know how they are exposed in DI, and if it's possible to use them right now.

**Comment by acanimal** [comment]
I though you simply work to use bins in the first call, not on the rest of proposal. 
As I said here (https://github.com/CartoDB/deep-insights.js/issues/164#issuecomment-185623785) that works fine and created a new issue to implement the new properties: https://github.com/CartoDB/deep-insights.js/issues/209. Now I now they are implemented on windshaft I start working allow use them on DI.
