### ISSUE TITLE
The last datum can’t be selected in histogram widgets

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#165]
(vg. value 500, but histogram only selects up to 499.999999999
cc @abelvm

**Comment by AbelVM** [comment]
Example:

My dataset includes a row with only one point with a value of 50K pretty isolated from the rest of the points

![img](http://i.imgur.com/aWetYfW.png)

If I try to select the final bin where that point is located, the filter sent to the server is :

```javascript
{"layers":[{"undefined-c45":{"min":47916.66708333318,"max":49999.99999999984}}]}
```
So that point is out of bounds, and therefore, the response is empty

**Comment by acanimal** [comment]
@AbelVM please check the data you receive from server. On DI code the filter range goes from start/end of the bin selected. Take a look and confirm me data is ok or bad.

**Comment by AbelVM** [comment]
When selecting the last bin, the request 

`http://ashbu.cartocdn.com/abelcdb/api/v1/map/87f48f35473aeb942a8c6d6220079d5d:1455537003099.8198/1/widget/undefined-c50?start=0.01&end=49999.99999999984&bins=48&bbox=2.0788192749023433,41.31533668176989,2.213058471679687,41.47990435892969`

So no 50K there.

Response:

`{"bin_width":1041.66645833333,"bins_count":48,"bins_start":0.01,"nulls":0,"avg":55.7128599674636,"bins":[{"bin":0,"min":0.01,"max":1041.12,"avg":49.7386820458359,"freq":1100706},{"bin":1,"min":1041.7,"max":2080.31,"avg":1444.39977673326,"freq":2553},{"bin":2,"min":2085,"max":3123,"avg":2600.85193116635,"freq":523},{"bin":3,"min":3130,"max":4152.77,"avg":3613.10697674419,"freq":129},{"bin":4,"min":4213.89,"max":5157.47,"avg":4784.15181818182,"freq":55},{"bin":5,"min":5225,"max":6178.35,"avg":5619.37303030303,"freq":33},{"bin":6,"min":6269.02,"max":7197.84,"avg":6693.408,"freq":15},{"bin":7,"min":7292.07,"max":8310.6,"avg":7735.82333333333,"freq":6},{"bin":8,"min":8630,"max":9042,"avg":8836,"freq":2},{"bin":9,"min":9405.48,"max":10316.11,"avg":9940.615,"freq":6},{"bin":10,"min":10890,"max":11439,"avg":11158.68,"freq":3},{"bin":11,"min":12000,"max":12108.98,"avg":12070.9933333333,"freq":3},{"bin":12,"min":12570,"max":13404,"avg":12987,"freq":2},{"bin":13,"min":14000,"max":14000,"avg":14000,"freq":1},{"bin":14,"min":15000,"max":15000,"avg":15000,"freq":2},{"bin":15,"min":15752.86,"max":15752.86,"avg":15752.86,"freq":1},{"bin":17,"min":17982.24,"max":17982.24,"avg":17982.24,"freq":1},{"bin":18,"min":19600,"max":19600,"avg":19600,"freq":1},{"bin":19,"min":19964.15,"max":19964.15,"avg":19964.15,"freq":1},{"bin":23,"min":25000,"max":25000,"avg":25000,"freq":1},{"bin":36,"min":37622.33,"max":37622.33,"avg":37622.33,"freq":1},{"bin":47,"min":50000,"max":50000,"avg":50000,"freq":6}],"type":"histogram"}`

(The value of start is allways 0.01 no matter the selection)

**Comment by javisantana** [comment]
FYI https://github.com/CartoDB/cartodb.js/issues/926

**Comment by AbelVM** [comment]
I knew I've come across this before...

**Comment by acanimal** [comment]
Fixed with https://github.com/CartoDB/cartodb.js/pull/1107
