### ISSUE TITLE
time series crashes with static layers when a range is selected

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#167]

**Comment by AbelVM** [comment]
> Uncaught TypeError: Cannot read property 'setRange' of undefined
module.exports.cdb.core.View.extend._onBrushEnd @ histogram-view.js:67
triggerEvents @ backbone.js:370
triggerApi @ backbone.js:356
eventsApi @ backbone.js:155
Events.trigger @ backbone.js:346
onBrushEnd @ chart.js:665
event @ d3.js:504
(anonymous function) @ d3.js:540
brushend @ d3.js:9289
(anonymous function) @ d3.js:1119
