### ISSUE TITLE
mywidget.update() forces an update to everything in the dashboard

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/deep-insights.js#168]
Let's say, if you update an histogram, changing only its number pf bins, the update command propagates to the whole dashboard dataviews, widgets and map, and it's not needed at all.

**Comment by javisantana** [comment]
I think you should be using `refresh` to reload the data. In any case changing bins updates the data right now

**Comment by AbelVM** [comment]
In this very case, I do want to avoid updating the data of this widget and the propagation of this update

**Comment by javisantana** [comment]
I don't get you, if you don't want to update the widget, why do you call `update`

**Comment by AbelVM** [comment]
How would you change the title or number of bins of a widget without using update?

**Comment by javisantana** [comment]
probably related to https://github.com/CartoDB/cartodb.js/issues/1069

**Comment by acanimal** [comment]
I'm workin with latest master DI and v4 cartodb.js and I'm unable to reproduce the ise. I have two layers and a couple of widgets on each one and when I update the histogram bins only that widgets is updated. No other network requests are done, neither the map or other widgets.

What I realized is changing a widget tile changes the widgetModel class but not the view.
