### ISSUE TITLE
When you hide a layer, the widgets linked to the layers with index higher than the hidden one will crash on filtering:

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/deep-insights.js#169]
Imaging you have 2 layers and hide the first one. Then the widgets of the second layer trigger off a crash.
 
I mean, they display the data and updates OK, but as soon as you try to filter through them, it crahses with a 400 error and a message like: 

`"Error creating the map instance on Windshaft: Cannot read property 'type' of undefined”
windshaft-map.js:77`

**Comment by acanimal** [comment]
@AbelVM this is solved in the last cartodb.js v4 branch (https://github.com/CartoDB/cartodb.js/pull/1113). It is more/less a workaround, it will problably fail if you reorder layers, so we are working on https://github.com/CartoDB/cartodb.js/issues/1020 to fix it in all uses cases.
