### ISSUE TITLE
Space between charts on zoomed histogram is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#176]
![screen shot 2016-02-15 at 11 36 09](https://cloud.githubusercontent.com/assets/132149/13046311/6475989a-d3d8-11e5-8fd8-57dbed6a09e4.png)

@javierarce @piensaenpixel would need some help with the svg changes needed

**Comment by saleiva** [comment]
Also, please note that the alignement is buggy.
![screen shot 2016-02-15 at 11 43 13](https://cloud.githubusercontent.com/assets/132149/13046476/513a9158-d3d9-11e5-9638-ec043aff6e19.png)

**Comment by piensaenpixel** [comment]
- Fix the margins in 176-fix_histogram
- I'll talk with @javierarce about the height
