### ISSUE TITLE
Map isn't centered as specified in .json or by code

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/deep-insights.js#190]
Looks like the center of the map is displaced up-left due to the dashboard's panels. 

When you set the view through .json sttings, setView(), .panTo()... you don't get what you set

cc @xavijam

**Comment by javisantana** [comment]
I think this is probably related to CSS

**Comment by xavijam** [comment]
Probably related with https://github.com/CartoDB/cartodb.js/pull/1104.

**Comment by xavijam** [comment]
The problem is, sequentially:

- Deep insights dashboard needs to create the map, using `createVis` from CartoDB.js lib.
- When the previous step happens, there is no widgets in the view, so the widgets column hasn't been added to the document, so map center is calculated taking into account all the available space.
- After that, widgets will start to appear, creating the widgets column, but map was already centered and losing some space and without triggering any "re-center" method or event, what provokes a problem of weird center at the beginning.

**Comment by xavijam** [comment]
Yesterday we released a fix for Deep insights dashboards, where a function is called within CartoDB.js ([vis.js](https://github.com/CartoDB/cartodb.js/blob/v4/src/vis/vis.js#L441)) when widgets are initialized, what do you think about this approach?

```js
...
  instantiateMap: function () {
    this.mapView.invalidateSize();
    if (this.mapConfig.view_bounds_ne && this.mapConfig.view_bounds_sw) {
      this.mapView.showBounds(
        [
          this.mapConfig.view_bounds_ne,
          this.mapConfig.view_bounds_sw
        ]
      );
    } else {
      this.map.setCenter(this.mapConfig.center, this.mapConfig.zoom);
    }
    this._instantiateMap();
  },
...
```

**Comment by AbelVM** [comment]
Ya he visto el PR, awesome!!



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=abel@cartodb.com&idSignature=22>

On Wed, Feb 17, 2016 at 9:55 AM, Javier Álvarez Medina <
notifications@github.com> wrote:

> Yesterday we released a fix for Deep insights dashboards, where a function
> is called within CartoDB.js (vis.js
> <https://github.com/CartoDB/cartodb.js/blob/v4/src/vis/vis.js#L441>) when
> widgets are initialized, what do you think about this approach?
>
> ...
>   instantiateMap: function () {
>     this.mapView.invalidateSize();
>     if (this.mapConfig.view_bounds_ne && this.mapConfig.view_bounds_sw) {
>       this.mapView.showBounds(
>         [
>           this.mapConfig.view_bounds_ne,
>           this.mapConfig.view_bounds_sw
>         ]
>       );
>     } else {
>       this.map.setCenter(this.mapConfig.center, this.mapConfig.zoom);
>     }
>     this._instantiateMap();
>   },...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/deep-insights.js/issues/190#issuecomment-185103146>
> .
>



-- 

*Abel Vázquez Montoro*
Solutions Engineer

*CartoDB*
Plaza de Callao 4, 2 28013 Madrid
www.cartodb.com
