### ISSUE TITLE
histogram with zoom filter does not work with vector rendering

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#201]
- open airbnb example
- select the histogram as show in the image
![screen shot 2016-02-17 at 2 50 49 pm](https://cloud.githubusercontent.com/assets/30147/13111542/9f5aa856-d586-11e5-9881-f1c2ad51c7ba.png)

there should be points in the map but show nothing

**Comment by alonsogarciapablo** [comment]
I think this is fixed now... Could you please confirm @fdansv?

**Comment by fdansv** [comment]
Yep!

![hist](https://cloud.githubusercontent.com/assets/3707222/13146671/25935438-d657-11e5-9604-5e48f5098147.gif)

**Comment by javisantana** [comment]
\o/
