### ISSUE TITLE
vector maps does not update the map when bbox changes

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#216]
- load a map
- pan the map but only a little bit so no new tiles are loaded but features are pulled out 

widgets aren't updated and they should

**Comment by alonsogarciapablo** [comment]
I'm guessing the problem here is that the d3 layer is not triggering the `featuresChanged` event because there aren't new tiles.@fdansv can confirm this

**Comment by fdansv** [comment]
Yes, but there's also the fact that right now we're not doing a strict bounding box check, but checking whether the features are within tiles that are completely or partly visible.

**Comment by javisantana** [comment]
but the widgets in the case should be the ones requesting the data because of the map movement, right?

**Comment by alonsogarciapablo** [comment]
You are right @javisantana. Working on it!

**Comment by alonsogarciapablo** [comment]
I implemented [this PR](https://github.com/CartoDB/cartodb.js/pull/1122) that makes the dataview fetch data from the d3 layer when map bounds change. Still, there's some work to be done by @fdansv so that the features returned by the D3 layer are more accurate with what the user is seeing.
