### ISSUE TITLE
Spacing between formula title and formula number is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#218]
![screen shot 2016-02-18 at 16 25 21](https://cloud.githubusercontent.com/assets/132149/13148128/40c2b096-d65c-11e5-8250-02bc589f19e2.png)

Take a look at the sketch file

**Comment by piensaenpixel** [comment]
Fixed - https://github.com/CartoDB/deep-insights.js/pull/223
