### ISSUE TITLE
histogram zoom raises an exception in vector

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#227]
- open an example
- filter using a histogram
- click on zoom

you get this
![screen shot 2016-02-19 at 5 09 28 pm](https://cloud.githubusercontent.com/assets/30147/13181150/e5f8fef6-d72b-11e5-91cb-aa63d9bab03d.png)

**Comment by alonsogarciapablo** [comment]
@javisantana can you pull the `v4` branch of CartoDB.js and try again? It's working for me...

**Comment by javisantana** [comment]
fixed somewhere :D
