### ISSUE TITLE
HIstogram normalization hides insights

### ISSUE THREAD

**Issue by javisantana** [CartoDB/deep-insights.js#252]
The image attached shows a gps track of a car in a race track. That zone in the viewport is where the car breaks (really hard). I also added two widgets that show the acceleration (ax and ay). 

When I zoom to that zone I'm expecting to see what's going on in this zone in the histograms but I don't see it because the values are really small compared with the whole dataset.

My point is: we should allow to the user to choose if they want global normalized histograms or not.

![screen shot 2016-02-24 at 6 12 32 pm](https://cloud.githubusercontent.com/assets/30147/13293992/46c71368-db22-11e5-8be0-79ba3937d3f4.png)

In the other hand, when the data for an histogram is around 0 we should show a bold marker in the 0 so you see pretty clear where the positive and negative values are.

cc @javierarce @urbanphes

**Comment by javisantana** [comment]
something like

![screen shot 2016-02-24 at 6 12 32 pm](https://cloud.githubusercontent.com/assets/30147/13294308/9cd4e284-db23-11e5-9a98-bdf49f7f4f6b.png)

**Comment by urbanphes** [comment]
1) When we have a histograms with values really small we can put the action “Zoom” automatically. We give the possibility to show more details. 

![histogram_value_small](https://cloud.githubusercontent.com/assets/14546701/13314000/a51a2286-dba2-11e5-8f52-1263fb267da8.png)





2) I think one solution is to have one of the vertical bars coincides with “0”. 

![histogram_0](https://cloud.githubusercontent.com/assets/14546701/13314004/ab74cf78-dba2-11e5-87cc-d5e23574d7e9.png)

**Comment by AbelVM** [comment]
Similar use case: when analyzing a percent or ratio value, normalization almost deletes the data

![img](http://i.imgur.com/bA712PJ.png)

**Comment by AbelVM** [comment]
Looks like **normalize_histogram** branch fixes this and works flawlessly

**Comment by javisantana** [comment]
For the record, I did a quick hack to fix @AbelVM problems -> https://github.com/CartoDB/deep-insights.js/compare/normalize_histogram?expand=1

could you @javierarce check if you like the solution?

**Comment by AbelVM** [comment]
Looks like the value of the "normalized" flag is inverted, isn't it?

**Comment by saleiva** [comment]
We should:
- hide the grey bars when having that option deactivated
- make this toggleable from the "..." icon on the top right of the widgets.

**Comment by saleiva** [comment]
Remember the option on the subbmenu

**Comment by javisantana** [comment]
one thing I noticed, the swtichers are actually switchers but look like regular action buttons

**Comment by saleiva** [comment]
What?

2016-03-15 17:09 GMT+01:00 javi santana <notifications@github.com>:

> one thing I noticed, the swtichers are actually switchers but look like
> regular action buttons
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/CartoDB/deep-insights.js/issues/252#issuecomment-196900458
>



-- 
Sergio Alvarez Leiva

**Comment by javisantana** [comment]
![widgets_norm](https://cloud.githubusercontent.com/assets/30147/13785484/0b543efc-ead4-11e5-82b8-17efc8302f91.gif)

this how should work?

**Comment by saleiva** [comment]
Let's change the text, and think if we don't want to change also the
buckets

2016-03-15 17:33 GMT+01:00 javi santana <notifications@github.com>:

> [image: widgets_norm]
> <https://cloud.githubusercontent.com/assets/30147/13785484/0b543efc-ead4-11e5-82b8-17efc8302f91.gif>
>
> this how should work?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/CartoDB/deep-insights.js/issues/252#issuecomment-196910531
>



-- 
Sergio Alvarez Leiva

**Comment by javisantana** [comment]
How would work the buckets thing? remove the ones without data? That would require some days of development

**Comment by saleiva** [comment]
:(

Ok, let's try like it is now and open a new ticket with that if needed

2016-03-15 18:00 GMT+01:00 javi santana <notifications@github.com>:

> How would work the buckets thing? remove the ones without data? That would
> require some days of development
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub:
>
> https://github.com/CartoDB/deep-insights.js/issues/252#issuecomment-196922982
>



-- 
Sergio Alvarez Leiva
