### ISSUE TITLE
Make examples work w/o local tiler setup

### ISSUE THREAD

**Issue by viddo** [CartoDB/deep-insights.js#26]
Problems:
- Some examples are setup to work with a local user/vis
- Some examples are setup to work with staging user/vis
- Examples are assuming dev env to work (using the uncompressed bundle)
- Examples only work after a local clone and `grunt dev` run

TODOs:
- [ ] setup "official documentation" account on staging, until underlying (tiler etc.) code is pushed to production
- [ ] setup vis on the documentation account, update examples to use those instead of personal/local accounts

The requirements for examples for end-users are not the same for development user, I think we should reconsider how they are setup

**Comment by alonsogarciapablo** [comment]
I think the two reasons why this examples are still not stable are:

1. We're using a custom viz.json format (the Editor is not able to serve it yet).
2. Examples depend on some features of Windshaft-CartoDB and Windshaft that are not stable and available in production yet.

**Comment by viddo** [comment]
https://github.com/CartoDB/deep-insights.js/commit/c0c319479c2b889c2d913526035cc5c4527b0abd An example that's relying on a specific setup, so even if providing a "local config" one needs to have the same vis setup for the example to work as expected.

**Comment by viddo** [comment]
I think this should be solved once #80 is done, so closing
cc @javisantana
