### ISSUE TITLE
[categories] Null category with 0 count

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/deep-insights.js#269]
Weird behaviour
![img](http://i.imgur.com/C9dsPKb.png)

It comes from the server:

![img](http://i.imgur.com/faBRux2.png)

**Comment by xavijam** [comment]
I feel it should be placed in Windshaft-cartodb repository.
cc @rochoa

**Comment by rochoa** [comment]
It will be addressed at https://github.com/CartoDB/Windshaft/issues/468
