### ISSUE TITLE
Small bug in widget options dropdown

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#292]
![screen shot 2016-03-17 at 18 55 57](https://cloud.githubusercontent.com/assets/132146/13855690/f0bd1ccc-ec71-11e5-8f0a-94cafb1385be.png)

**Comment by AbelVM** [comment]
[Normalize] option should have a tick/checkbox/whatever to display its state. It may be possible that looking at the histogram itself, you can't say if it's enabled or not.

**Comment by xavijam** [comment]
Yeah, we should set, normalize or "unnormalize"(?) depending on the state.
