### ISSUE TITLE
Change option label when histogram is already normalized

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#295]
It should appear as "Normalize" when it is in normal state and "Unnormalize" (?) when it is already "normalized".

cc @javisantana

**Comment by javisantana** [comment]
this is design issue, I already talked about it https://github.com/CartoDB/deep-insights.js/issues/252#issuecomment-196900458

**Comment by xavijam** [comment]
Changed assignment

**Comment by xavijam** [comment]
I guess this issue is not needed anymore, there will be a toggle and the text won't change. Closing!
