### ISSUE TITLE
style by category keeps reinstantiating maps

### ISSUE THREAD

**Issue by rochoa** [CartoDB/deep-insights.js#319]
## STR
1. Open examples/populated-places.html.
1. Apply auto style on "Country" widget
1. Pan the map

## Current behaviour
After pan is finished a new map instantiation happens and all tiles are requested again.

## Expected behaviour
After applying/sending the new style and when panning no new map instantiation requests should happen.

**Comment by fdansv** [comment]
This is happening with the category widget because is resetting the cartocss each time the map is panned or zoomed.
