### ISSUE TITLE
Category Widget: Polygon

### ISSUE THREAD

**Issue by makella** [CartoDB/deep-insights.js#331]
### Ramp
- Use [Bold](https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js#L253-L263) from CartoColors
- The color for **other** shows above in the combination for 11 colors and should be set to `#A5AA99`

### CartoCSS
- The style should be adjusted depending on the basemap. 

**Positron**
```
#layer {
   polygon-opacity: 0.9;
   line-color: #FFFFFF;
   line-width: 0.5;
   line-opacity: 1;

   [category=1]{
      polgyon-fill: #7F3C8D;
   }
   ...
}
```

**Dark Matter**
```
#layer {
   polygon-opacity: 0.9;
   line-color: #000000;
   line-width: 0.5;
   line-opacity: 1;

   [category=1]{
      polgyon-fill: #7F3C8D;
   }
   ...
}
```
### Example

**Positron**
![screen shot 2016-04-25 at 4 37 53 pm](https://cloud.githubusercontent.com/assets/1566273/14801148/6f4a617a-0b04-11e6-86a7-c393e6d4c7b9.png)  
![screen shot 2016-04-25 at 4 18 43 pm](https://cloud.githubusercontent.com/assets/1566273/14801155/77e8afe4-0b04-11e6-9cf8-976a70490eed.png)

**Dark Matter**
![screen shot 2016-04-25 at 4 18 29 pm](https://cloud.githubusercontent.com/assets/1566273/14824740/4996b380-0b94-11e6-9f3c-473d0f917b0d.png)  
![screen shot 2016-04-25 at 4 37 32 pm](https://cloud.githubusercontent.com/assets/1566273/14824746/4f08029c-0b94-11e6-9a62-6ed4823010c9.png)

cc @andrewxhill @saleiva

**Comment by javisantana** [comment]
hey, there is one problem, we have more basemaps, I guess we should categorize them by light/dark right?

**Comment by makella** [comment]
oh like all the basemaps that are available in the editor?

**Comment by javisantana** [comment]
yes

**Comment by makella** [comment]
ok i'll add a separate issue here and classify each one for you. does that sound ok?

**Comment by makella** [comment]
here you go: https://github.com/CartoDB/deep-insights.js/issues/333
