### ISSUE TITLE
Histogram Widget: Points Colored by Value (Near Normal / A Shape)

### ISSUE THREAD

**Issue by makella** [CartoDB/deep-insights.js#332]
### Data Distribution
- Near Normal / A Shape Distribution

### Classification Method
- Typically, we would classify this distribution with a Standard Deviation classification where values above and below the mean are emphasized.
- For this kind of classification, it is best to use a diverging ramp where there are neutral colors in the middle and two different colors on either side representing high and/or low values.

### Ramp
- Use [Geyser](https://github.com/CartoDB/CartoColor/blob/master/cartocolor.js#L233-L239) from CartoColors

### CartoCSS
- Styling is the same for Postiron and Dark Matter
- Note that the line color of each marker is a slightly darker version of its fill
- Please note that I've adjusted the default `marker-width` size. I see that we are reading in `'marker-width: {{markerWidth}};'` but wondering if that can be adjusted to `'marker-width: 6;'` for any color by value instance.

```
#layer {
   marker-fill-opacity: 0.9;
   marker-line-color: #FFFFFF;
   marker-line-width: 1;
   marker-line-opacity: 1;
   marker-width: 6;
   marker-fill: #d3d3d3;
   marker-allow-overlap: true;

   [ value <= value] {
      marker-fill: #ca562c;
      marker-line-color: darken(#ca562c,10);
   }
   [ value <= value] {
      marker-fill: #e6a272;
      marker-line-color: darken(#e6a272,10);
   }
...
}
```

### Example

**Positron**  
![screen shot 2016-04-29 at 5 22 23 pm](https://cloud.githubusercontent.com/assets/1566273/14932145/58a479dc-0e2f-11e6-9e14-e87e40e07f50.png)

**Dark Matter**  
![screen shot 2016-04-29 at 5 22 38 pm](https://cloud.githubusercontent.com/assets/1566273/14932138/4e8a8d92-0e2f-11e6-91bc-80424b5baf84.png)

cc: @andrewxhill @saleiva

**Comment by javisantana** [comment]
Hey @makella 

how do we differenciate between a "Near Normal / A Shape" and a "Clustered" distribution?

**Comment by makella** [comment]
@javisantana don't laugh but **clustered** in pink. **Near normal** or with a little different shape, **A** in blue. 

Does that help?

<img width="486" alt="screen shot 2016-05-05 at 9 11 39 am" src="https://cloud.githubusercontent.com/assets/1566273/15044316/e17613f8-12a1-11e6-82b2-30f8530f440a.png">

**Comment by makella** [comment]
Another thought that might help... I think in statistics they call 'clustered' bimodal? so when the data are clustered, Jenks is best because it maximizes the variance between the classes and minimizes the variance within every class.

With the near normal / A we want to emphasize the middle and then either side. For this method, the standard deviation of the distribution is used to set the cutpoints above and below the average.

**Comment by javisantana** [comment]
ok, perfect, clustered is clearly jenks
