### ISSUE TITLE
Should all autostyling defaults be the same?

### ISSUE THREAD

**Issue by makella** [CartoDB/deep-insights.js#343]
@fdansv @saleiva @javisantana 

do you guys think that we should use the same color palettes for all autostyling regardless of geometry? for example, for a J distribution for lines and polygons, should we use what we've defined for points? 

I started thinking about this yesterday and want to get other opinions...

what do you think?

if we go that route, I will make sure that the defaults I defined work across all geometries but want to see what you guys think first.

**Comment by makella** [comment]
my concern is that it will be confusing to the user if we switch the color palettes so much through different geometries specifically for auto styling. Or maybe it depends on the way the user is aggregating their data for the widgets?

and we don't have to worry about two similar styles being on the map (regardless of geometry) at the same time because only one widget can be activated at a time, right?

**Comment by saleiva** [comment]
I think so, yeah!

On Monday, 9 May 2016, Mamata Akella <notifications@github.com> wrote:

> my concern is that it will be confusing to the user if we switch the color
> palettes so much through different geometries specifically for auto
> styling. Or maybe it depends on the way the user is aggregating their data
> for the widgets?
>
> and we don't have to worry about two similar styles being on the map
> (regardless of geometry) at the same time because only one widget can be
> activated at a time, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/deep-insights.js/issues/343#issuecomment-217893571>
>


-- 
Sergio Alvarez Leiva

**Comment by makella** [comment]
Ok, me too. I'll keep the tickets going by geometry type but make sure that the ramp selected for a particular distribution works across all geometries. 

Thanks, @saleiva !

**Comment by makella** [comment]
cc @andrewxhill
