### ISSUE TITLE
Category Colors not Current

### ISSUE THREAD

**Issue by makella** [CartoDB/deep-insights.js#351]
@fdansv I see in `category-colors.js` that the colors from cartocolor `Bold` have been defined, but I don't see those colors drawing consistently in the examples -- I thought I saw them in the populated places example, but it isn't consistent. Also, for category "Other" I have a color defined from the palette which is `#A5AA99`.  Right now it looks like "Other" is defaulting to a yellow.

**Comment by fdansv** [comment]
@makella is this still happening?

**Comment by makella** [comment]
nope looks to be good! thanks for checking in.
