### ISSUE TITLE
Mobile issues in the public view

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#385]
- [x] Interaction in mobile is pretty hard. Tested on Android
- [x] Keyboard appears and disappears when you click on search on category widget

**Comment by saleiva** [comment]
Prioritizing since more maps are being published with widgets

**Comment by nobuti** [comment]
Could you list the troubles you found?

**Comment by saleiva** [comment]
Yep, 

Filtering is very hard (you have very low precission). 
On the other hand, once you've filtered, moving the lateral bars is almost impossible.

**Comment by jorgesancha** [comment]
Moving to NEXT to prioritise Style with Icons and some backend stuff cc @saleiva

**Comment by piensaenpixel** [comment]
@nobuti maybe the problem with the scroll could be fixed in CSS, but I need to check it

**Comment by piensaenpixel** [comment]
This is the most important problem:

![widgets](https://cloud.githubusercontent.com/assets/1214201/22796321/4ad98fde-eefa-11e6-98bb-34343002e9f3.gif)

It's impossible to filter in the histogram because the scroll's event intercept the filter

**Comment by jorgesancha** [comment]
thanks @piensaenpixel 👏

**Comment by noguerol** [comment]
So, just for giving a little more of context: we need this for a demo we are building for the Telefonica's booth in Mobile World Congress. MWC will start in two weeks, but the deadline is even tighter because next Wed 15 is the last day we can test this on the Surface device that will run this map.

**Comment by nobuti** [comment]
@saleiva @xavijam @jorgesancha @piensaenpixel we have a problem with the category widget and the search thing. Doing focus on the field triggers the keyboard to appear. So the viewport is resized. When resized the dataviews change, so all the widgets views are rendered again. So the field that had got the focus doesn't exist anymore, so the focus is gone, and the keyboard hides. And the cycle begins again. Basically, this feature is unusable in mobile.

**Comment by nobuti** [comment]
For the time being, I'm going to hide the search button in devices with touch support.

**Comment by xavijam** [comment]
Not sure, what could we do better here?

**Comment by nobuti** [comment]
Honestly, the changes involved in order to fix it are too deeper to consider right now. Given that the user is able to filter categories even without searching, it's not that bad.

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Deployed in production.

**Comment by noguerol** [comment]
I agree with the decision, but let's start thinking on a more long term solution: https://github.com/CartoDB/deep-insights.js/issues/520
