### ISSUE TITLE
Style is passed postprocessed at the embeds

### ISSUE THREAD

**Issue by fdansv** [CartoDB/deep-insights.js#386]
When using Deep Insights standalone, or when operating widgets on the embed, the style related to the layer `this.layer.get('meta').cartocss` doesn't return preprocessed turbo-carto styles, but styles that have been converted into regular cartocss. This is a problem when trying to keep certain properties from the original style on autostyling.

@alonsogarciapablo can you think of any way to get the preprocessed cartocss?

**Comment by alonsogarciapablo** [comment]
As discussed with @fdansv I don't think there's a way now to get that pre-processed cartocss in CartoDB.js. We use named maps in embeds, and so CartoDB.js doesn't have that information...

**Comment by fdansv** [comment]
Yeah, I think the approach to keeping properties has to be different on the client...
