### ISSUE TITLE
Auto-style fails when having # on category names

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#408]
![screen shot 2016-07-06 at 14 20 32](https://cloud.githubusercontent.com/assets/132149/16617603/dd7002a0-4384-11e6-9f42-7245a70510ff.png)

Within the builder, styling by category on the same column works correctly

**Comment by saleiva** [comment]
@rochoa, how would you expect the category names for turbo-carto?

**Comment by rochoa** [comment]
Original issue: https://github.com/CartoDB/cartodb/issues/5419
