### ISSUE TITLE
Histogram selection is not being properly restored from URL

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/deep-insights.js#416]
# STR:

1. Go into the embed of a map with a histogram widget
2. Apply a selection on the histogram
3. Refresh

# Expected result:

The selection is reapplied.

# Actual result:

No selection is visible in the histogram (it's appearance is exactly the same as before applying any selection) but the map visualization *is* indeed filtered.

**Comment by xavijam** [comment]
This problem will be solved here -> https://github.com/CartoDB/deep-insights.js/issues/445
