### ISSUE TITLE
It's redundant to ask for layer type when creating a layer

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/deep-insights.js#422]
It's compulsory to add `type` attrib as parameter when creating a layer, but the type is implicit in the function name:

```javascript
createCartoDBLayer({...type:'CartoDB'...})
createTorqueLayer({ ...type: 'Torque', ...})
...
```

It would be way simpler if the type is defined only once as a parameter instead of having 6 different functions:

```javascript
createLayer({...type:'CartoDB'...})
createLayer({ ...type: 'Torque', ...})
...
```

**Comment by xavijam** [comment]
Issue moved to [CartoDB/cartodb.js #1354](https://github.com/CartoDB/cartodb.js/issues/1354) via [**ZenHub**](https://www.zenhub.com/)
