### ISSUE TITLE
Setting a widget as non dynamic should reset the info on it to contain all the data.

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#431]
@saleiva commented on [Tue Jul 19 2016](https://github.com/CartoDB/cartodb/issues/8979)

#SMOKE_WD24 #SMOKE_WD17

**Comment by nobuti** [comment]
Closed by https://github.com/CartoDB/cartodb.js/commit/eacd654844924877bf04f08c4cd04a8f611c1ccb
