### ISSUE TITLE
State URL problems

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#445]
- [x] We need to make a map instantiation _without filters_, in order to get the full data range. If there is no filters applied, go ahead and request all widgets data. If there is any filter, make a second map instantiation with the filters, and then request all the widgets data.
- [x] Don't set state URL when the map is initialized.
- [x] Don't listen widgets change until all widgets and map have been started (it triggers URL changes when state change).
- [x] Don't store center and zoom, better to store bounding box, `ne` and `sw` (https://github.com/CartoDB/deep-insights.js/issues/444).

**Comment by xavijam** [comment]
cc @javisantana and @rochoa

**Comment by nobuti** [comment]
We found some issues with the histogram. Reopening.
