### ISSUE TITLE
When marking a widget as NON dynamic, we should disable also the capability for filtering from it

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#453]
@saleiva commented on [Tue Jul 05 2016](https://github.com/CartoDB/cartodb/issues/8523)

#SMOKE_WD24 #SMOKE_WD17

**Comment by donflopez** [comment]
Should I put some message, change the mouse icon or anything else?

**Comment by saleiva** [comment]
It would have to become as non interactive. So no mouse pointer changes, or anything like that.

**Comment by donflopez** [comment]
Now, the list has a `mouse: pointer` attr when `:hover` is active, so it seems that is a clickable element. If it's as a non interactive/ non filterable element, should I remove this attr from the item?

**Comment by saleiva** [comment]
yep!

**Comment by donflopez** [comment]
Ok! Thank you!

**Comment by saleiva** [comment]
I remember there was a different issue (which I can't find right now) to reset the widget as soon as marked as NON-dynamic, so the totals get shown. If not, what happened before is that the data shown depends on the position you have the map.

**Comment by saleiva** [comment]
Ha! Found it https://github.com/CartoDB/deep-insights.js/issues/431

**Comment by donflopez** [comment]
Yeah @saleiva!

That issue depends of some changes in the way layers/widgets are related with each other, I think that @nobuti is working on it!
