### ISSUE TITLE
Category widgets with the char '#' in one of the values fails when auto-styling

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#463]
@saleiva commented on [Thu Sep 29 2016](https://github.com/CartoDB/cartodb/issues/9952)

**Comment by donflopez** [comment]
I can't reproduce it.

I have this table:
<img width="486" alt="screen shot 2016-10-13 at 10 46 00" src="https://cloud.githubusercontent.com/assets/463462/19342643/f0d05754-9132-11e6-8263-490a5fcdc0d3.png">

And this widget:
<img width="287" alt="screen shot 2016-10-13 at 10 47 02" src="https://cloud.githubusercontent.com/assets/463462/19342654/fa97c7ae-9132-11e6-8cc7-29cff4c43e5b.png">

If I click on autostyling it works ok.
