### ISSUE TITLE
Widget auto-style color ramp should be always calculated with the total data and not with the bounding box

### ISSUE THREAD

**Issue by saleiva** [CartoDB/deep-insights.js#468]
Sometimes when you are looking at all the data it applies a color ramp.
And then, when zooming in and doing so again, it applies a different color ramp.

Which is kind of confusing. The color ramp should be always calculated with all the data.

#SMOKE_WD15

cc/ @javisantana

**Comment by donflopez** [comment]
This issue depends of #469 & @cartodb/cartodb.js#1450 PR's
