### ISSUE TITLE
Remove default styling properties that block vector rendering

### ISSUE THREAD

**Issue by makella** [CartoDB/deep-insights.js#549]
As discussed in this issue (https://github.com/CartoDB/cartodb.js/issues/1670) and this issue (https://github.com/CartoDB/cartodb.js/pull/1624) we have some default properties blocking vector rendering. Specifically, `polygon-gamma` and `line-comp-op`. 

I think Auto-Style is actually the best use of these properties but I understand why we need to remove them. 

Basically, we need to remove `polygon-gamma` and `line-comp-op` properties from here:
https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/auto-style/auto-styler.js#L41-L50

cc @donflopez @saleiva

**Comment by makella** [comment]
One thing we need to test is how we should modify the default Auto-Style CartoCSS with these properties removed.

I will test in Builder by modifying the Auto-Style CartoCSS to see what a suitable alternative is.

**Comment by makella** [comment]
So if we remove those properties, there is no effect the real problem with Auto-Style on polygons is still this unresolved issue with lines trying to ramp and not working:
https://github.com/CartoDB/deep-insights.js/issues/518

We should definitely test when modifications are made.  For polygons, all we need is to not overwrite line-color when auto-style is enabled.

**Comment by xavijam** [comment]
Hey @makella, taking care of this one in https://github.com/CartoDB/deep-insights.js/issues/557. Closing this one!

Thanks! 💋 .
