### ISSUE TITLE
Use ::outline for polygon line properties

### ISSUE THREAD

**Issue by rochoa** [CartoDB/deep-insights.js#557]
To make it fully compatible with Vector rendering, we need to use different rendering layers when using lines in polygons.

So at any time use a `line-color` property in a polygons dataset, we should respect the existing style if it uses a `::outline` approach, or we must use the `::outline` approach.

References:
- https://github.com/CartoDB/deep-insights.js/issues/549.
- https://github.com/CartoDB/cartodb/issues/7723.

**Comment by xavijam** [comment]
Merged, deployed, 🚀 !
