### ISSUE TITLE
Examples are not working

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#628]
I've tried with `easy.html` and there are two errors until you success to display a deep-insights dashboard.

- `Uncaught ReferenceError: L is not defined`: It needs to add the Leaflet library.
- `get is undefined` within `create-dashboard.js` file: seems like `cdb.core.Loader` is not exported.

**Comment by ivanmalagon** [comment]
`cdb.Loader` was 🔥  months ago. Instead on relying of it to load the vizJSON, we should download in another way to refactor the examples.
