### ISSUE TITLE
Missing hover in widgets

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/deep-insights.js#640]
Related - https://github.com/CartoDB/design/issues/1035

cc @rubenmoya @matallo

**Comment by matallo** [comment]
whoa, many elements I didn't have in my radar, let me prioritize this for this next sprint

**Comment by matallo** [comment]
in production! 🚀

**Comment by piensaenpixel** [comment]
<3

**Comment by piensaenpixel** [comment]
but one thing, if i change the color-widget to a custom color, the hover doesn't work :(

**Comment by rubenmoya** [comment]
It seems like we broke it with this change: https://github.com/CartoDB/deep-insights.js/pull/641/files#diff-11ebf18b812ac90a72a6c99eff5f150eR1444, it was using the `currentFillColor` and we change it to a hardcoded one.

**Comment by jesusbotella** [comment]
Yes, it is my fault :(

**Comment by rubenmoya** [comment]
I did the CR, and someone else did the acceptance, and none of us noticed, don't blame yourself, these things happen, let's fix it and focus on what we've learned about widgets autostyling :)

**Comment by matallo** [comment]
removing from board for better tracking

**Comment by rubenmoya** [comment]
In production! 🚀
