### ISSUE TITLE
allow for histograms to be customized in diJSON

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/deep-insights.js#71]
Right now the `bins` value is ignored when setting up a histogram widget, like in [this example](https://github.com/CartoDB/widgets-examples/blob/gh-pages/airbnb_madrid_oct_2015_listings.html#L51). 

The following would be ideal for creating histograms IMO:

1. No `bins` key means default to Freeman-Diaconis bin calculations
2. `bins: n` gives `n` bins equally spaced over the range of the data (a separate key `scale` could have `equal` or `log` scales for the binning)
3. `bins: [v1, v2, v3, v4, ..., vn]` gives the `n` bin bounds for `n-1` bins

cc @rochoa 

ref: https://github.com/CartoDB/Windshaft/issues/414

**Comment by xavijam** [comment]
It is already done so closing :).
