### ISSUE TITLE
Update CartoAssets version to 0.1.15

### ISSUE THREAD

**Issue by javierarce** [CartoDB/deep-insights.js#79]
This requires updating the entry file for the SCSS.

**Comment by javierarce** [comment]
I'll do this in the `cartoassets` branch… ok, @xavijam?

**Comment by xavijam** [comment]
:+1:, I'll need to update to .16. It is coming :) -> https://github.com/CartoDB/CartoAssets/pull/16

**Comment by javierarce** [comment]
Excellent :) Pushed!
