### ISSUE TITLE
Torque time-series example makes browser unresponsive

### ISSUE THREAD

**Issue by viddo** [CartoDB/deep-insights.js#88]
Broken on master.

![screen shot 2016-01-27 at 15 26 20](https://cloud.githubusercontent.com/assets/978461/12616239/6a89224c-c50a-11e5-87ba-1e428e2ff736.png)

- Keeps happening even if widgets are commented out, so seems unrelated to any specific widgets/dataviews.
- No error in the console (the local-config thing is not relevant)
- First symptom is some kind of infinite loop somewhere, causing the browser to eventually hang and go _oh snap!_

![screen shot 2016-01-27 at 15 29 14](https://cloud.githubusercontent.com/assets/978461/12616300/c3a168da-c50a-11e5-8866-bf11acf1331d.png)

**Comment by viddo** [comment]
@rochoa was this the same issue you mentioned yesterday or is this one new?

**Comment by rochoa** [comment]
Well, I don't know if they are related. But I've suffered the issue (I don't have STR yet) with mapnik layers, so I wouldn't say it's the same thing.

**Comment by viddo** [comment]
#104 these missing data could be related, BUT it seems like the WindshaftMap is not sending any data:

```
POST /user/orgowner/api/v1/map?stat_tag=4c07a35{"layers":[{"type":"torque","options":{"sql":"select * from mwc13","cartocss":"Map{-torque-frame-count:256;-torque-resolution:1;-torque-aggregation-function:'count(cartodb_id)';-torque-time-attribute:'end_at';-torque-data-aggregation:linear;-torque-animation-duration:30;}#mwc13{\n  comp-op: lighter;\n  marker-fill-opacity: 0.9;\n  marker-line-color: #FFF;\n  marker-line-width: 0;\n  marker-line-opacity: 1;\n  marker-type: ellipse;\n  marker-width: 6;\n  marker-fill: #0F3B82;\n}#mwc13[frame-offset=1] {\n marker-width:8;\n marker-fill-opacity:0.45; \n}\n#mwc13[frame-offset=2] {\n marker-width:10;\n marker-fill-opacity:0.225; \n}","cartocss_version":"2.1.1","interactivity":[],"widgets":{}}}]}
```
^-- widgets is emtpy

**Comment by viddo** [comment]
@alonsogarciapablo any ideas? was the torque use-case handle code removed perhaps?

**Comment by javisantana** [comment]
are the tables somewhere to put them in production, specially mwc13

**Comment by javisantana** [comment]
Yes, it's a loop, the way to fix these kind of issues is:

1) run the example with developer tools open in "scripts" tab
2) hit pause to see the stack
3) start to put breakpoints until you find the loop

Basically setUrls calls setReady -> setKeys -> Modify the model -> setUrls ....

Adding a setImmediate breaks the signal loop, will do a PR to cartodb.js

**Comment by viddo** [comment]
:tada: :kiss:

**Comment by javisantana** [comment]
fixed here https://github.com/CartoDB/cartodb.js/pull/1041
