### ISSUE TITLE
Search in widgets is case sensitive and it shouldn't

### ISSUE THREAD

**Issue by xavijam** [CartoDB/deep-insights.js#9]
Reported by @saleiva in https://github.com/CartoDB/cartodb.js/issues/925.

**Comment by xavijam** [comment]
I'm not sure about this, but @rochoa should confirm it.

**Comment by rochoa** [comment]
@saleiva can you provide an example?

At least backend is case insensitive as per https://github.com/CartoDB/Windshaft/blob/3aa173851876c16d85d74a17b6c36a4c6a923ad4/test/acceptance/widgets/aggregation.js#L266-L284

**Comment by rochoa** [comment]
@saleiva I'm closing this one, feel free to re-open if you find any issue.
