### ISSUE TITLE
Change all dataviews/widgets attrs to use snake_case

### ISSUE THREAD

**Issue by viddo** [CartoDB/deep-insights.js#96]
To be consistent with the rest of the APIs
From https://github.com/CartoDB/deep-insights.js/pull/95/files#r51449072

**Comment by xavijam** [comment]
Change ```aggregationColumn``` to underscore will provoke changes in the Maps API too (https://github.com/CartoDB/Windshaft/blob/940736271f255d24b603d5f22560372f2f65171f/test/acceptance/widgets/aggregation.js#L117).

**Comment by viddo** [comment]
@rochoa we discussed changing the data attrs (sent in requests/responses) to be snake_case for API consistency, in today's checking meeting. We thought it would only affect the frontend… is this problematic to change for the APIs (e.g. Windshaft)?
cc @javisantana

**Comment by xavijam** [comment]
@viddo, assigning to you since you are on it.

**Comment by viddo** [comment]
done in #138
